spring:
  application:
    name: appointment-service
  r2dbc:
    url: r2dbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:6543/postgres?pgbouncer=true
    username: postgres.bpswqweiwbacnoxkzrbc
    password: "05102002"
  flyway:
    enabled: true
    url: jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:6543/postgres?pgbouncer=true
    user: postgres.bpswqweiwbacnoxkzrbc
    password: "05102002"
    schemas: appointment_schema
    baseline-on-migrate: true

server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

logging:
  level:
    com.revup.appointment_service: DEBUG
    org.springframework.r2dbc: DEBUG
