apiVersion: v1
kind: Secret
metadata:
  name: firebase-secret
  namespace: revup-backend
type: Opaque
stringData:
  FIREBASE_PROJECT_ID: "revup-1b6d0"
  FIREBASE_PRIVATE_KEY_ID: "your-private-key-id"
  FIREBASE_PRIVATE_KEY: "-----BEGIN PRIVATE KEY-----\nYOUR_PRIVATE_KEY_HERE\n-----END PRIVATE KEY-----"
  FIREBASE_CLIENT_EMAIL: "firebase-adminsdk@your-project.iam.gserviceaccount.com"
  FIREBASE_CLIENT_ID: "your-client-id"
---
apiVersion: v1
kind: Secret
metadata:
  name: gemini-secret
  namespace: revup-backend
type: Opaque
stringData:
  GEMINI_API_KEY: "AIzaSyDblfdFB83HjWrgPRtK6DhEvgpVH6qokxM"




