apiVersion: v1
kind: Secret
metadata:
  name: firebase-secret
  namespace: revup-backend
type: Opaque
stringData:
  FIREBASE_PROJECT_ID: "revup-1b6d0"  # UPDATE THIS
  FIREBASE_PRIVATE_KEY_ID: "your-private-key-id"  # UPDATE THIS
  FIREBASE_PRIVATE_KEY: "-----BEGIN PRIVATE KEY-----\nYOUR_PRIVATE_KEY_HERE\n-----END PRIVATE KEY-----"  # UPDATE THIS
  FIREBASE_CLIENT_EMAIL: "firebase-adminsdk@your-project.iam.gserviceaccount.com"  # UPDATE THIS
  FIREBASE_CLIENT_ID: "your-client-id"  # UPDATE THIS
---
apiVersion: v1
kind: Secret
metadata:
  name: gemini-secret
  namespace: revup-backend
type: Opaque
stringData:
  GEMINI_API_KEY: ""  # UPDATE THIS




