spring:
  application:
    name: employee-service
  r2dbc:
    url: r2dbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres?schema=employee_schema
    username: postgres.ytrfhppmjhwgkjmumaqo
    password: ${DB_PASSWORD:your-password-here}
  flyway:
    enabled: true
    url: jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres?currentSchema=employee_schema
    user: postgres.ytrfhppmjhwgkjmumaqo
    password: ${DB_PASSWORD:your-password-here}
    schemas: employee_schema
    baseline-on-migrate: true

server:
  port: 8087

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

logging:
  level:
    com.revup.employee_service: DEBUG
    org.springframework.r2dbc: DEBUG
