server:
  port: 8081

spring:
  application:
    name: chatboat_service

  ai:
    google:
      genai:
        api-key: "YOUR GEMINI API-KEY"
        chat:
          options:
            model: "gemini-2.0-flash-lite"

external:
  api:
    base-url: "http://localhost:8083/"
    path: "api/service-types"
    timeout-seconds: 10
