server.port: 8083

spring:
  application:
    name: RevUp-Appointment-Service
  datasource:
    url: jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:6543/postgres
    username: postgres.bpswqweiwbacnoxkzrbc
    password: "05102002"
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      pool-name: AppointmentServiceHikariPool
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

---
spring:
  config:
    activate:
      on-profile: dev, no_eureka

eureka:
  client:
    enabled: false