spring:
  application:
    name: project-service
  r2dbc:
    url: r2dbc:postgresql://aws-0-us-east-1.pooler.supabase.com:6543/postgres?schema=project_schema
    username: postgres.ykqzvugolgnudbcgklam
    password: Riyad@123
  flyway:
    enabled: true
    url: jdbc:postgresql://aws-0-us-east-1.pooler.supabase.com:6543/postgres?currentSchema=project_schema
    user: postgres.ykqzvugolgnudbcgklam
    password: Riyad@123
    schemas: project_schema
    baseline-on-migrate: true
    locations: classpath:db/migration
  codec:
    max-in-memory-size: 10MB

server:
  port: 8086

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    com.revup.project_service: DEBUG
    org.springframework.r2dbc: DEBUG
    io.r2dbc.postgresql: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
